#!/bin/sh

# This program finds the most recently changed file in the
# package sources. Used to make writing Makefile rules for
# this package that bit easier.
#
# Ignore description and documentation files as these are generated by
# Roxygen

find stagePop -type f ! -iname 'DESCRIPTION' -a ! -iname 'NAMESPACE' -a ! -iwholename '*\.svn**' -a ! -iname '*.Rd' -printf "%T@\0%p\0" | gawk '
    {
        if ($0>max) {
            max=$0; 
            getline mostrecent
        } else 
            getline
    } 
    END{print mostrecent}' RS='\0'
